services:
  - type: web
    name: snow-wild
    env: node
    region: oregon
    plan: standard
    buildCommand: "npm install && npm build"
    startCommand: "npm run resetDb & npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET_KEY
        fromSecret: jwt-secret-key
    autoDeploy: true # Trigger auto-deployments on every commit to the main branch
    branch: main # The branch to auto-deploy from
    healthCheckPath: "/health"
    disk:
      name: my-disk
      mountPath: /var/data
      sizeGB: 10
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: postgres
    type: postgres
    plan: free
    region: oregon
    diskSizeGB: 5
    user: postgres
    password: "postgres"
    database: snowwild
