import { AuthContext } from "@/contexts/AuthContext";
import styles from "@/styles/Home.module.css";
import ListMaterial from "@/user/components/ListMaterial";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user } = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>SnowWild</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className} `}>
        <div className={styles.description}>
          <ListMaterial />
        </div>
      </main>
    </>
  );
}
