import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import ListMaterial from "@/components/ListMaterial";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SnowWild</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <ListMaterial />
          <p>
            {/* Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code> 
            Hello Snow wild 🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞*/}
          </p>
          {/* Start paragraph ===> mettre dans la page LOGIN 
          <Link
            href="/auth/logout"
            replace={true}
            className="px-6 py-2 text-white transition duration-500 ease-out bg-red-700 rounded-lg hover:bg-red-800 hover:ease-in hover:underline"
          >
            Se déconnecter
          </Link> End paragrah */}
          
  
        </div>

       

       
      </main>
    </>
  );
}
