name: test-docker

on: push 



jobs: 
    test-back: 
        runs-on: ubuntu-latest
        services:
            # Label used to access the service container
            postgres:
              # Docker Hub image
              image: postgres
              # Provide the password for postgres
              env:
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: snowwild
              # Set health checks to wait until postgres has started
              options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
              ports:
                # Maps tcp port 5432 on service container to the host
                - 5432:5432
      

        steps: 
            - name: 👀 Check out code
              uses: actions/checkout@v2
            - name: Goto back and run tests
              run: cd backend && npm i && npm run testCI

