name: test-docker

on: push 

jobs: 
    test-back: 
        runs-on: ubuntu-latest
        steps: 
            - name: 👀 Check out code
              uses: actions/checkout@v2
            - name: Goto back and run tests
              run: cd backend && npm i && npm run testCI

